name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x" # Or whichever version you're using

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Newman
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults

      #Run the Postman collection
      - name: Run Postman Collection
        run: |
          newman run Demo-My.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darktheme  >  testResults/runreport1.html
